refresh: 10
theme: default
colour: true
sort: change
reverse: true
prices: USD
stocks:
    - MSFT # stock
    - VTV # etf
    - ^DJI # index
cryptos:
    - BTC # crypto
    - ETH # crypto
    - DOGE # crypto
forexes:
    - CADUSD # forex
    - USDGBP # forex
others:
    - ^TNX # bond
    - GC=F # future
    - 600519.SS # sse
