refresh: 10
theme: default
sort: change
reverse: true
stocks:
    - MSFT # stock
    - VTV # etf
    - ^DJI # index
cryptos:
    - BTC # crypto
    - ETH # crypto
forexes:
    - CADUSD # forex
    - USDGBP # forex
others:
    - ^TNX # bond
    - GC=F # future
    - RY.TO # tsx
