# This is an example configuration file. See the documentation for details.

refresh: 10
theme: default
sort: change
reverse: true
stocks:
    - MSFT # stock
    - VTV # etf
    - ^DJI # index
cryptos:
    - BTC # crypto
    - ETH # crypto
forexes:
    - CAD # forex
    - GBP # forex
others:
    - ^TNX # bond
    - GC=F # future
    - RY.TO # tsx
